### ISSUE TITLE
Use Sonus for speech recognition

### ISSUE THREAD

**Issue by evancohen** [jakkra/SmartMirror#1]
Hey @jakkra! I noticed that you're using Google Cloud Speech and Snowboy for speech recognition and I thought I'd point out [Sonus](https://github.com/evancohen/sonus), which might be useful for your project.

Would love it if you could give me some feedback on it.

Awesome job on the mirror by the way - looks super awesome!

**Comment by jakkra** [comment]
Thanks, I don't see what it does that I haven't implemented myself. Looks like a nice project, but can't see how it would improve anything for me.
