### ISSUE TITLE
Add better configuration margins 

### ISSUE THREAD

**Issue by jakkra** [jakkra/SmartMirror#11]
Currently values for margins are hard coded, those should perhaps be extracted for easier configuration.

Also declare the style in App.js as a `const style =... ` instead of writing the style in the render method

**Comment by ghosh** [comment]
Hey, I can take this up. Can you clarify a bit more which margins you want to make configurable? Is the one inlined in App.js?

**Comment by jakkra** [comment]
Yes in App.js, however I'm doing some layout changes. I will update you when it's done. And then you can add some configuration for it. I'm also making the mirror easier to run, so I recommend waiting until I'm done. Hacktoberfest doesn't start until 1 October anyway, so pull requests before doesn't count ;)

**Comment by ghosh** [comment]
Ok great! Thank you.

**Comment by jakkra** [comment]
Feel free to take on this now, should be a quick fix :)

**Comment by ghosh** [comment]
@jakkra I am working on this now. How do you feel about making exclusive a styles object in the config? something like this:-

```js
  styles: {
    textScale: '0.8em' // relative font-size of text
    paddingTop: '5%', // space from the top edge
    paddingLeft: '7%', // space from the left edge
    paddingRight: '6%', // space from the right edge
    paddingBottom: '0%' // space from the bottom edge
  },
```

Also, would we also include Row margins here?

**Comment by jakkra** [comment]
@ghosh Exactly what I was thinking :+1: 
Yes row margin would also be nice to have there, however I'm unsure if you would want the same row margin between all components, currently I have different margins between my components. So maybe all components should have configurable margins. I'm planning on making some kind of config for the placement of the different modules, so maybe I'll handle module margins there instead.
