### ISSUE TITLE
Voice recognition for English should be supported 

### ISSUE THREAD

**Issue by jakkra** [jakkra/SmartMirror#12]
Involves adding configuration for Google cloud speech language and transliting my voice parser to English

**Comment by binora** [comment]
Hi, I'd like to take this one up. I believe `languageCode` option in `speech/stream.js' can be set up as a configurable param ? Is this the right direction ? Let me know. btw, kudos to this amazing work!

**Comment by jakkra** [comment]
Yes, that's step one and to extract that to config files. However we still need to be able to parse the text and do actions depending on what was said. Therefore speech/command_classify.js and speech/reminder_parser.js needs to be translated to english. However a good start is to just do the command_classify.js, it should be easier.

What needs to be done is translating the arrays at the top of the file. For example:
`const bedroomSynonymsEnglish= ['bed', 'the bed', 'bedroom', 'bedrooms', 'the bedroom', 'the bedrooms'];`

`const onSynonymsEnglish = ['turn on', 'on', 'start', '...'];
`
What also needs to be done is to find a good way to handle in the command_classify.js for how to handle multiple languages. Maybe extracting translations to it's own file? And command_classify.js doesn't know anything about what language is used and just let the new translation file handle it.

**Comment by binora** [comment]
Okay, I'll try and give it a shot for multiple languages using this library (if it's possible) https://github.com/mashpie/i18n-node
else, I'll start off with just english arrays like you said in `command_classify.js`

**Comment by jakkra** [comment]
That library is for handling translation of API calls in different languages, right? Which isn't exactly what we want. It doesn't seem like it's possibly to translate the frontend React by using it. But I guess it could be used for handling the translation for the voice parsing. Feel free to try it out, but I think it will be easier to just have a json file for each language, and depending on the configured language, you just use a different json file.
