### ISSUE TITLE
hue.js should not be hardcoded for my setup

### ISSUE THREAD

**Issue by jakkra** [jakkra/SmartMirror#14]
https://github.com/jakkra/SmartMirror/blob/master/util/hue.js

**Comment by binora** [comment]
hey, I'd like to help on this one. Can you give some context  ?

**Comment by jakkra** [comment]
Sure! There is two things, first one is to make hue.js generic by adding the hue lights you have at home in the config. The config will be the name of each light set up in the Philips hue app. And the name of the group of lights that will correspond to "all".
So in hue.js lights should be kept in either a map or array. Also a config for which lights should be auto off needs to be added.
So the exported method 'light: function(name, options)' would find the correct light from the array of all hue lights.
