### ISSUE TITLE
Rename the two config files to config.js.default and add config.js to gitignore

### ISSUE THREAD

**Issue by jakkra** [jakkra/SmartMirror#17]
This way you can have your own local copy of the config without conflicting with others.

https://github.com/jakkra/SmartMirror/blob/master/config.js

https://github.com/jakkra/SmartMirror/blob/master/client/src/config.js

Also update README

**Comment by htalat** [comment]
hey, can i take this up?

**Comment by jakkra** [comment]
Sure thing! Go on :+1:
