### ISSUE TITLE
GPIOs for PIR and button should be configureable 

### ISSUE THREAD

**Issue by jakkra** [jakkra/SmartMirror#22]
Add to both config files and use the config in initialization of PIR and button.

**Comment by wildan3105** [comment]
Hi, I'd like to contribute to this project. What is the starting point regarding this issue?

**Comment by jakkra** [comment]
In util/button.js and util/motion.js the GPIOs are hard coded. Those should use values specified in the config files instead

**Comment by binora** [comment]
@wildan3105  you still doing this ?  Let me know .
