### ISSUE TITLE
Find a suitable test framework and create tests for command_classify

### ISSUE THREAD

**Issue by jakkra** [jakkra/SmartMirror#33]
Would be nice to have some tests for the voice parser (https://github.com/jakkra/SmartMirror/blob/master/speech/command_classify.js) . Since multi language is supported for controlling the mirror now.

Input to the test would be phrases in the supported languages and then check that the output is the correct command code in https://github.com/jakkra/SmartMirror/blob/master/speech/speech_command.js

**Comment by xingwang** [comment]
Due to overlapping keywords, I had to remove a few to keep all commands, toggles, and locations unique so that your "stringContainsItemFromList" method will get the right result.
