### ISSUE TITLE
Add translation to client/Weather.js and client/Tasks.js

### ISSUE THREAD

**Issue by jakkra** [jakkra/SmartMirror#38]
Känns som == Feels like
Vindhastighet == Wind speed

Att handla == To buy / Shopping list

**Comment by binora** [comment]
curious about the approach. Could add the phrases in <language>.json as with meanings in arrays and then access `0th` index in the respective clients ? Do you have anything else in mind ?

**Comment by jakkra** [comment]
Maybe we can do like this in language.json https://gist.github.com/jakkra/bfd372955a6467480eb50e3a8e25054c?
Then in synonyms `module.exports = require(currentLanguageFile.speech);`
