### ISSUE TITLE
Port the static web app to React

### ISSUE THREAD

**Issue by jakkra** [jakkra/SmartMirror#50]
It's used to control the mirror from an arbitrary device with a browser. It just has a lot of buttons and each button links to some url with parameters. Not much logic is used.

Currently it's aweful and hard to maintain, would be awesome if it could be rewritten in React. 

A start would be to split html and js into seperate files at least.

It's located under `client/webApp-move2build`.

**Comment by Banb4n** [comment]
I will take a look at this ✅

**Comment by ruandev** [comment]
Hello.
Its very interesting project. I'll take a look at this.

**Comment by agoiabel** [comment]
@ruandev, are you still working on it, I love to collaborate if possible.
