### ISSUE TITLE
Upgrade to latest version of React

### ISSUE THREAD

**Issue by jakkra** [jakkra/SmartMirror#53]
Should not be too many changes required.

**Comment by gigobyte** [comment]
I'll have a take on it.

**Comment by jakkra** [comment]
@gigobyte Awesome, also here are some warning currently generated:
![warnings](https://user-images.githubusercontent.com/4318648/46433856-41346a80-c752-11e8-9bf6-6465ae496fa4.png)

**Comment by gigobyte** [comment]
Unfortunately, I haven't been able to build the app on Windows due to Visual C++ errors.

**Comment by jakkra** [comment]
@gigobyte Ah, never tried building it on Windows, I should do that.
Have you tried downgrading Node, I had some errors when I used newer lately.
```
sudo npm cache clean -f
sudo npm install -g n
sudo n 7.6.0
```

**Comment by gigobyte** [comment]
Tried that, the node version is not the problem.
